import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import Papa from 'papaparse';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DATA_DIR = path.resolve(__dirname, '../public/data');

const researchData = [
  {
    id: "1",
    title: "Seg2Reg-Net: An Explainable AI Analysis of Predictive Limitations in Cattle Weight Estimation",
    thumbnail_url: "/wall/undergrad.jpeg",
    description: "- Developed Seg2Reg-Net, integrating Attention U-Net with regression for non-contact cattle weight estimation\n- Improved prediction accuracy, reducing RMSE from 53.36 to 41.56\n- Implemented image segmentation to remove background noise and enhance anatomical feature extraction\n- Applied LIME and SHAP for model interpretability and pixel-level attribution\n- Identified key body regions (mid-body, hindquarters) influencing weight predictions\n- Analyzed spurious correlations and background biases to refine data preprocessing pipelines",
    abstract: "Accurate measurement of cattle body weight is critical for improving nutrition, health management, breeding strategies, and market value. Automated methods using computer vision and deep learning provide a promising non-contact alternative for weight estimation. However, these approaches face challenges because 2D images often fail to capture full body volume, key anatomical details, and variations caused by lighting, occlusion, or background clutter, which lead to inconsistent and inaccurate predictions. To address these challenges, we propose Seg2Reg-Net, an end-to-end framework that integrates an Attention U-Net-based segmentation module with a regression network. The proposed model achieves enhanced predictive accuracy, reducing RMSE from 53.36 with standard regression to 41.56. Pixel-level explainability techniques, including LIME and SHAP, are applied to systematically interpret model predictions. LIME highlights top positive contributors such as the mid-body and hindquarters, while SHAP reveals positive, negative, and near-zero effect regions, exposing spurious correlations and background influences. These findings contribute to the refinement of data preprocessing and model design, facilitating the practical application of accurate weight predictions in livestock management.",
    status: "published",
    award: "",
    year: "2025",
    topics: "Computer Vision & Imaging, Clinical AI & Deep Learning",
    authors: "Mst. Fahmida Sultana Naznin|https://github.com/fahmidahossain ; Arnab Dey ; Debojit Pandit ; Ahanaf Ferdous ; Rakib Islam ; Hasan Ibna Akbar ; Jannatun Noor ; A. B. M. Alim Al Islam",
    links: "code:https://github.com/fahmidahossain/Seg2Reg-Net ; paper:https://doi.org/10.1145/3777555.3777559 ; video:https://youtu.be/qIXg9vJ6hZM?si=5liTMbMY_VbdWT0r",
    media: "image:/wall/undergrad.jpeg ; youtube:https://youtu.be/qIXg9vJ6hZM?si=5liTMbMY_VbdWT0r",
    is_featured: "true",
    featured_order: "4",
    venue: "12th NSysS 2025 (ACM)",
    external_url: "https://doi.org/10.1145/3777555.3777559",
    has_demo: "true",
    demo_url: "https://youtu.be/qIXg9vJ6hZM?si=5liTMbMY_VbdWT0r",
    bibtex: ""
  },
  {
    id: "2",
    title: "CSTRL: Context-Driven Sequential Transfer Learning for Abstractive Radiology Report Summarization",
    thumbnail_url: "/wall/research_1.jpg",
    description: "- Developed CSTRL (Context-driven Sequential Transfer Learning) for generating clinical Impressions from Findings\n- Applied sequential transfer learning with Fisher information matrix regularization to prevent catastrophic forgetting\n- Improved summarization quality with significant gains in BLEU (+56.2% BLEU-1, +84.3% BLEU-3) and ROUGE metrics\n- Ensured clinical factual consistency and context preservation in generated radiology reports\n- Evaluated comprehensively on MIMIC-CXR and Open-I clinical benchmark datasets\n- Successfully addressed domain complexity, specialized medical terminology, and diagnostic error sensitivity",
    abstract: "A radiology report comprises several sections, including the Findings and Impression of the diagnosis. Automatically generating the Impression from the Findings is crucial for reducing radiologists' workload and improving diagnostic accuracy. Pretrained models that excel in common abstractive summarization problems encounter challenges when applied to specialized medical domains largely due to complex terminology and the necessity for accurate clinical context. Such tasks in medical domains demand extracting core information, avoiding context shifts, and maintaining proper flow. Misuse of medical terms can lead to drastic clinical errors. To address these issues, we introduce a sequential transfer learning framework that ensures key content extraction and coherent summarization. Sequential transfer learning often faces challenges like initial parameter decay and knowledge loss, which we resolve with Fisher information matrix regularization. Using MIMIC-CXR and Open-I datasets, our model, CSTRL — Context-driven Sequential TRansfer Learning — achieved state-of-the-art performance, showing 56.2% improvement in BLEU-1, 40.5% in BLEU-2, 84.3% in BLEU-3, 28.9% in ROUGE-1, 41.0% in ROUGE-2, and 26.5% in ROUGE-L score over benchmark studies. We also analyze factual consistency scores while strictly preserving the medical context. Our code is publicly available.",
    status: "published",
    award: "",
    year: "2025",
    topics: "Clinical NLP & LLMs, Clinical AI & Deep Learning",
    authors: "Mst. Fahmida Sultana Naznin|https://github.com/fahmidahossain ; Adnan Ibney Faruq ; Mostafa Rifat Tazwar ; Md Jobayer ; Md. Mehedi Hasan Shawon ; Md Rakibul Hasan",
    links: "code:https://github.com/fahmidahossain/Report_Summarization ; paper:https://doi.org/10.18653/v1/2025.findings-acl.1360 ; video:https://youtu.be/jyerIT_txG0?si=9RaI6rVtJXlwX0CI",
    media: "image:/wall/research_1.jpg ; youtube:https://youtu.be/jyerIT_txG0?si=9RaI6rVtJXlwX0CI",
    is_featured: "true",
    featured_order: "1",
    venue: "ACL 2025 (Findings)",
    external_url: "https://doi.org/10.18653/v1/2025.findings-acl.1360",
    has_demo: "true",
    demo_url: "https://github.com/fahmidahossain/Report_Summarization",
    bibtex: ""
  },
  {
    id: "3",
    title: "CBRS: Cognitive Blood Request System with Bilingual Dataset and Dual-Layer Filtering for Multi-Platform Social Streams",
    thumbnail_url: "/wall/research_1.jpg",
    description: "- Developed CBRS (Cognitive Blood Request System) to detect and parse urgent blood donation requests from social media streams\n- Built a cost-efficient, dual-layered multi-platform architecture for real-time noise reduction\n- Curated a novel 11K multilingual dataset (Bengali, English, and transliterated Bengali) with adversarial negatives\n- Achieved 99% accuracy and precision in blood request detection, outperforming benchmark models\n- Fine-tuned Llama-3.2-3B via LoRA, achieving 92% zero-shot parsing accuracy (+41.54% over base model)\n- Outperformed GPT-4o-mini and Gemini-2.0-flash while slashing token usage by 35X",
    abstract: "Urgent blood donation seeking posts and messages on social media often go unnoticed due to the overwhelming volume of daily communications. Traditional app-based systems, reliant on manual input, struggle to reach users in low-resource settings, delaying critical responses. To address this, we introduce the Cognitive Blood Request System (CBRS), a multi-platform framework that efficiently filters and parses blood donation requests from social media streams using a cost-efficient dual-layered architecture. To do so, we curate a novel dataset of 11K parsed blood donation request messages in Bengali, English, and transliterated Bengali, capturing the linguistic diversity of real social media communications. The inclusion of adversarial negatives further enhances the robustness of our model. CBRS achieves an impressive 99% accuracy and precision in filtering, surpassing benchmark methods. In the parsing task, our LoRA fine-tuned Llama-3.2-3B model achieves 92% zero-shot accuracy, surpassing the base model by 41.54% and exceeding the few-shot performance of GPT-4o-mini, Gemini-2.0-flash, and other LLMs while resulting in a 35X reduction in input token usage. This work lays a robust foundation for scalable, inclusive information extraction in time-sensitive, object-focused tasks.",
    status: "published",
    award: "",
    year: "2026",
    topics: "Clinical NLP & LLMs, LLMs & Multi-Agent",
    authors: "Mst. Fahmida Sultana Naznin|https://github.com/fahmidahossain ; Anik Saha|https://github.com/aaniksahaa ; Zia Ul Hassan Abdullah ; Anisa Binte Asad ; K G Subarno Bithi ; A. B. M. Alim Al Islam",
    links: "code:https://github.com/aaniksahaa/CBRS ; paper:https://github.com/aaniksahaa/CBRS",
    media: "image:/wall/research_1.jpg",
    is_featured: "true",
    featured_order: "2",
    venue: "ACL 2026 (Findings)",
    external_url: "https://github.com/aaniksahaa/CBRS",
    has_demo: "true",
    demo_url: "https://github.com/aaniksahaa/CBRS",
    bibtex: ""
  },
  {
    id: "4",
    title: "Relational Anatomical Reasoning for Anatomically Consistent 3D Brain Tumor Segmentation",
    thumbnail_url: "/wall/research_1.jpg",
    description: "- Introduced relational anatomical reasoning to enforce morphological consistency in 3D brain tumor segmentation\n- Modeled multi-parametric MRI sub-region containment hierarchy (Whole Tumor, Tumor Core, Enhancing Tumor)\n- Formulated structure-preserving topological losses to prevent disconnected and implausible predictions\n- Evaluated on multi-modal BraTS volumetric benchmark datasets\n- Reduced 95% Hausdorff Distance and boundary errors while achieving competitive Dice similarity scores\n- Delivered robust, clinically reliable segmentations suitable for neuro-oncology and surgical planning",
    abstract: "Multi-parametric magnetic resonance imaging (mpMRI) enables comprehensive assessment of brain tumors; however, automated 3D segmentation methods often produce anatomically implausible predictions, such as disconnected tumor fragments or invalid anatomical containment relationships across sub-regions. To address this fundamental limitation, we present a relational anatomical reasoning framework that explicitly integrates anatomical knowledge into 3D neural segmentation. Our architecture couples high-resolution volumetric representations with an anatomical relational reasoning engine that captures the biological nesting and spatial adjacency of whole tumor (WT), tumor core (TC), and enhancing tumor (ET) regions. By penalizing topological violations through a structure-preserving loss, the model guarantees morphological validity across all volumetric slices. Comprehensive evaluations on the BraTS benchmark demonstrate that our approach significantly reduces Hausdorff distances and boundary errors while achieving competitive Dice scores against leading 3D segmentation architectures, offering a principled foundation for clinical radiotherapy planning and neurosurgical intervention.",
    status: "preprint",
    award: "",
    year: "2026",
    topics: "Computer Vision & Imaging, Clinical AI & Deep Learning",
    authors: "SM Nuruzzaman Nobel ; Mst. Fahmida Sultana Naznin|https://github.com/fahmidahossain ; Maxine Tan ; Mohammad Ali Moni",
    links: "paper:https://arxiv.org/",
    media: "image:/wall/research_1.jpg",
    is_featured: "false",
    featured_order: "999",
    venue: "Under review — IEEE Transactions on Medical Imaging",
    external_url: "https://arxiv.org/",
    has_demo: "false",
    demo_url: "",
    bibtex: ""
  },
  {
    id: "5",
    title: "MedSegNet-X: Hybrid Noise-Enhanced Diffusion based Medical Image Segmentation with ConvNeXt Transformer",
    thumbnail_url: "/wall/research_1.jpg",
    description: "- Developed MedSegNet-X, a hybrid diffusion framework for robust medical image segmentation\n- Introduced Adaptive Hybrid Noise Layer simulating realistic imaging degradations (Gaussian, salt-and-pepper, uniform noise)\n- Integrated Fourier Transform Blocks, ConvNeXt modules, and self-supervised Transformers for local-global feature synergy\n- Designed dual-stage refinement architecture with composite loss for progressive boundary sharpening\n- Achieved state-of-the-art results across DRIVE (97.56%), STARE (99.75%), Kvasir-SEG (97.83%), and Brain MRI (98.76%)\n- Demonstrated superior structural continuity, noise resistance, and boundary precision for computer-aided diagnosis",
    abstract: "Medical image segmentation remains a fundamental yet challenging task due to noise, imaging artifacts, anatomical variability, and weak boundary contrast across clinical modalities. Although convolutional neural networks and transformer-based models have achieved promising performance, they often struggle to jointly capture fine-grained structural details and long-range contextual dependencies, while existing diffusion-based approaches typically rely on limited noise formulations that reduce robustness under complex imaging conditions. To address these limitations, we propose MedSegNet-X, a novel hybrid diffusion framework for robust medical image segmentation. The proposed model integrates an Adaptive Hybrid Noise Layer to simulate diverse real-world degradations through Gaussian, salt-and-pepper, and uniform noise distributions, together with Fourier Transform Blocks for frequency-domain feature learning, ConvNeXt blocks for local spatial representation, and a self-supervised transformer for global context modeling. In addition, a dual-stage refinement architecture with a composite objective function is introduced to progressively enhance segmentation quality and prediction consistency. We evaluate MedSegNet-X on four benchmark datasets spanning multiple imaging modalities, including DRIVE, STARE, Kvasir-SEG, and Brain MRI. Experimental results demonstrate that the proposed framework consistently outperforms strong CNN, transformer, and diffusion-based baselines, achieving up to 99.75% accuracy on STARE, 97.83% accuracy on Kvasir-SEG, 97.56% accuracy on DRIVE, and 98.76% accuracy with 88.94% IoU on Brain MRI. Qualitative and quantitative analyses further confirm that MedSegNet-X produces sharper boundaries, stronger structural continuity, and improved robustness to noise and artifacts, highlighting its potential for reliable computer-aided diagnosis and clinical decision support.",
    status: "preprint",
    award: "",
    year: "2025",
    topics: "Computer Vision & Imaging, Clinical AI & Deep Learning",
    authors: "SM Nuruzzaman Nobel ; Mst. Fahmida Sultana Naznin|https://github.com/fahmidahossain ; Md All Moon Tasir ; Asmaa Soliman Al-Moisheer ; Mohammad Ali Moni",
    links: "paper:https://arxiv.org/",
    media: "image:/wall/research_1.jpg",
    is_featured: "false",
    featured_order: "999",
    venue: "Under review — IEEE Transactions on Multimedia",
    external_url: "https://arxiv.org/",
    has_demo: "false",
    demo_url: "",
    bibtex: ""
  },
  {
    id: "6",
    title: "A Diffusion-Driven Intermediate Feature Fusion for Multi-Scale Structured Pattern Segmentation",
    thumbnail_url: "/wall/research_1.jpg",
    description: "- Developed DiffVesNet, a diffusion-driven encoder-decoder framework for retinal vessel and pattern segmentation\n- Introduced Diffusion-based Feature Map Fusion (Diff-FMF) for coherent intermediate multi-scale feature integration\n- Integrated Multi-Scale Context-Adaptive Transformers (MSCATs) for dynamic local-global attention gating\n- Utilized bidirectional GRU pathways to restore fine vascular continuity and thin capillary reconstruction\n- Addressed extreme class imbalance, low contrast, and confounding background artifacts in ophthalmic imaging\n- Achieved superior accuracies across DRIVE (98.16%), STARE (98.91%), CHASEDB1 (98.23%), and HRF (98.95%) datasets",
    abstract: "Feature fusion plays a critical role in medical image segmentation by balancing noisy high-resolution details with semantically rich but spatially coarse features. However, conventional fusion strategies often fail to effectively reconcile this multi-scale conflict, resulting in feature inconsistency and background interference. Diffusion-based operations promote spatial coherence and noise resilience, while attention mechanisms enable adaptive salience weighting. Yet their synergistic integration in deterministic fusion remains underexplored. In retinal vessel segmentation, these challenges are pronounced due to extreme scale variation, low-contrast thin capillaries, class imbalance, and confounding artifacts, leading to fragmented predictions and reduced sensitivity in state-of-the-art methods. To address these, we propose DiffVesNet, a novel encoder-decoder framework incorporating Diffusion-based Feature Map Fusion (Diff-FMF) and Multi-Scale Context-Adaptive Transformers (MSCATs). Diff-FMF performs intermediate fusion of encoder, decoder, and Bi-GRU features via diffusion-guided smoothing followed by self-attention, ensuring coherent integration and suppression of irrelevant signals. MSCATs dynamically gate local-global attention with inter-scale adaptive normalization for robust multi-scale contextual modeling, while bidirectional GRUs restore vascular continuity. Evaluated on DRIVE, STARE, CHASEDB1, and HRF datasets, DiffVesNet achieves superior accuracies of 98.16%, 98.91%, 98.23%, and 98.95%, respectively, with marked improvements in thin-vessel detection. Ablations confirm Diff-FMF's superiority over existing fusion techniques. DiffVesNet advances robust retinal vessel segmentation, facilitating early diagnosis of vascular abnormalities and setting a new benchmark for adaptive, diffusion-attention feature fusion in ophthalmic imaging.",
    status: "preprint",
    award: "",
    year: "2025",
    topics: "Computer Vision & Imaging, Clinical AI & Deep Learning",
    authors: "SM Nuruzzaman Nobel ; Mst. Fahmida Sultana Naznin|https://github.com/fahmidahossain ; Maxine Tan ; Asmaa Soliman Al-Moisheer ; Mohammad Ali Moni",
    links: "paper:https://arxiv.org/ ; video:https://youtu.be/WJvr_jstEfU?si=U_D_NUe4qR308Ohz",
    media: "image:/wall/research_1.jpg ; youtube:https://youtu.be/WJvr_jstEfU?si=U_D_NUe4qR308Ohz",
    is_featured: "true",
    featured_order: "3",
    venue: "Under review — Artificial Intelligence In Medicine",
    external_url: "https://arxiv.org/",
    has_demo: "true",
    demo_url: "https://youtu.be/WJvr_jstEfU?si=U_D_NUe4qR308Ohz",
    bibtex: ""
  },
  {
    id: "7",
    title: "BIGTNet: Anatomical Relational Reasoning for 3D Brain Tumor Segmentation",
    thumbnail_url: "/wall/research_1.jpg",
    description: "- Proposed BIGTNet (Brain Image Graph Transformer Network) for anatomically consistent 3D brain tumor sub-region segmentation\n- Integrated anatomical relational reasoning to capture multi-modal MRI structural dependencies across tumor sub-compartments\n- Designed graph transformer modules to model spatial topological interactions across volumetric MRI slices\n- Evaluated on BraTS multi-parametric benchmark datasets, achieving superior Dice coefficients and reduced boundary errors\n- Enhanced structural consistency and volumetric boundary delineation for surgical planning and oncological assessment",
    abstract: "Accurate 3D brain tumor segmentation from multi-parametric magnetic resonance imaging (mpMRI) is essential for neuro-oncological diagnosis, treatment planning, and longitudinal monitoring. However, brain tumors exhibit extreme heterogeneity in shape, texture, and intensity, alongside diffuse, infiltrative boundaries between sub-compartments—including the enhancing tumor, non-enhancing core, and peritumoral edema. Standard convolutional and transformer architectures frequently fail to enforce anatomical plausibility and cross-compartment topological constraints, yielding disconnected or morphologically inconsistent segmentations. We propose BIGTNet, a novel anatomical relational reasoning framework for 3D brain tumor segmentation. BIGTNet models hierarchical spatial and semantic relationships among tumor sub-regions by combining volumetric feature encoding with a dedicated graph transformer module. By formulating anatomical topology as a relational graph, BIGTNet explicitly reasons over inter-region dependencies and spatial adjacency. Evaluated extensively on the BraTS benchmarks, BIGTNet demonstrates substantial improvements in Dice similarity coefficient and Hausdorff distance across all tumor sub-structures while maintaining strict anatomical consistency, establishing a reliable paradigm for automated 3D neuro-radiological segmentation.",
    status: "preprint",
    award: "",
    year: "2025",
    topics: "Computer Vision & Imaging, Clinical AI & Deep Learning",
    authors: "SM Nuruzzaman Nobel ; Mst. Fahmida Sultana Naznin|https://github.com/fahmidahossain ; Maxine Tan ; Asmaa Soliman Al-Moisheer ; Mohammad Ali Moni",
    links: "paper:https://arxiv.org/",
    media: "image:/wall/research_1.jpg",
    is_featured: "false",
    featured_order: "999",
    venue: "Under review — IEEE Transactions on Medical Imaging",
    external_url: "https://arxiv.org/",
    has_demo: "false",
    demo_url: "",
    bibtex: ""
  },
  {
    id: "8",
    title: "PAN-ICA YOLO: Pyramid-Aware Neighbor-Only Inter-Channel Attention with Dense Optical Flow Mid-Fusion for Video Object Localization",
    thumbnail_url: "/wall/research_1.jpg",
    description: "- Developed motion-aware and multimodal enhancements within a YOLO11 framework for video object detection\n- Designed dense optical-flow mid-fusion with temporal stabilization and motion-salient feature gating\n- Introduced PAN-ICA (Pyramid-Aware Neighbor-Only Inter-Channel Attention) for multimodal RGB-IR feature fusion\n- Integrated multi-scale feature interaction using transformer-based attention across adjacent pyramid levels\n- Improved detection of small, obscured, and distant objects under severe motion blur and challenging illumination\n- Validated on IEEE Video and Image Processing Cup 2025 dataset with significant gains in mAP@50 and mAP@50-95",
    abstract: "Video object detection remains challenging, especially for small or distant targets that blur, deform, or blend into the background. We propose two complementary models within a YOLO11 framework that leverage motion and multimodal cues. First, a dense optical-flow mid-fusion pathway injects Farneback flow at pyramid level P4 (optionally P3), denoised in the frequency domain and temporally stabilized with exponentially weighted averaging after global motion compensation. A lightweight depthwise-pointwise mapping head and a gated residual fusion emphasize motion-salient regions while preserving static context. Second, we introduce Pyramid-Aware Neighbor-Only Inter-Channel Attention (PAN-ICA) for infrared (IR) and RGB fusion: dual backbones extract {P3, P4, P5} features; Stage 1 performs same-scale residual inter-channel attention via a transformer encoder with modality embeddings; Stage 2 applies neighbor-only cross-scale attention (P3<->P4, P4<->P5) with shared weights and residual refinement. The fused pyramid is processed by a PAN/FPN neck and decoded by a standard YOLO head. On the IEEE Video and Image Processing Cup 2025 dataset, the YOLO11m baseline achieves 99.13% Precision, 97.89% Recall, 99.63% mAP@50, and 88.84% mAP@50-95. Relative to this baseline, flow mid-fusion improves 0.68% Precision, 0.22% Recall, and 2.08% mAP@50-95; RGB-IR PAN-ICA increases 0.68%, 0.72%, 0.18%, and 2.25%, respectively. Our study contributes to the development of motion-aware, multimodal video object detection and localization.",
    status: "preprint",
    award: "",
    year: "2026",
    topics: "Computer Vision & Imaging, Clinical AI & Deep Learning",
    authors: "Adnan Ibney Faruq ; Mst. Fahmida Sultana Naznin|https://github.com/fahmidahossain",
    links: "paper:https://signalprocessingsociety.org/",
    media: "image:/wall/research_1.jpg",
    is_featured: "false",
    featured_order: "999",
    venue: "Under review — WACV 2026",
    external_url: "https://signalprocessingsociety.org/",
    has_demo: "false",
    demo_url: "",
    bibtex: ""
  },
  {
    id: "9",
    title: "MedCAR: Conflict-Aware Multi-Agent Reasoning for Multimodal Clinical AI",
    thumbnail_url: "/wall/research_1.jpg",
    description: "- Developed MedCAR (Medical Conflict-Aware Reasoner) for multimodal clinical multi-agent reasoning\n- Introduced systematic conflict detection and resolution across diagnosis, segmentation, and report generation outputs\n- Proposed probabilistic semantic conflict detection using neural entailment models\n- Designed Graph-Based Anatomical Consistency Learning (GACL) for structural plausibility verification\n- Applied bipolar weighted argumentation with adaptive trust estimation and principled abstention mechanism\n- Created ChestAgentBench-X benchmark with 503 multimodal chest X-ray cases containing explicit tool conflicts\n- Achieved 89.66% accuracy and 79.0% conflict detection accuracy, establishing safe autonomous clinical reasoning",
    abstract: "Large language model (LLM) agents show strong promise in multimodal clinical reasoning by orchestrating specialized tools for diagnosis, segmentation, and report generation. However, real-world medical toolchains often yield conflicting outputs—such as inconsistent disease predictions, anatomically implausible segmentations, and contradictory textual interpretations—undermining reliability and safety. We introduce MedCAR—Medical Conflict-Aware Reasoner, a conflict-aware multi-agent framework that systematically detects and resolves such inconsistencies through: (1) probabilistic semantic conflict detection via neural entailment, (2) Graph-Based Anatomical Consistency Learning (GACL) for structural plausibility, and (3) bipolar weighted argumentation with adaptive trust and principled abstention. We also present ChestAgentBench-X, a benchmark of 503 multimodal chest X-ray cases with explicit tool-level conflicts. MedCAR achieves 89.66% accuracy on this benchmark, with 79.0% conflict detection accuracy. This study establishes explicit conflict awareness as a key requirement for trustworthy clinical AI and highlights a path toward safer autonomous medical reasoning systems.",
    status: "published",
    award: "",
    year: "2025",
    topics: "Clinical AI & Deep Learning, LLMs & Multi-Agent",
    authors: "Mst. Fahmida Sultana Naznin|https://github.com/fahmidahossain ; Niloy Kumar Mondal ; Mohammad Ninad Mahmud Nobo ; Abrar Zahin Raihan ; Sheikh Azizul Hakim",
    links: "paper:https://arxiv.org/ ; video:https://youtu.be/jyerIT_txG0?si=9RaI6rVtJXlwX0CI",
    media: "image:/wall/research_1.jpg ; youtube:https://youtu.be/jyerIT_txG0?si=9RaI6rVtJXlwX0CI",
    is_featured: "true",
    featured_order: "5",
    venue: "Intl Conf on AI in Healthcare 2025",
    external_url: "https://arxiv.org/",
    has_demo: "true",
    demo_url: "https://youtu.be/jyerIT_txG0?si=9RaI6rVtJXlwX0CI",
    bibtex: ""
  },
  {
    id: "10",
    title: "DocTalkBN: A Novel Dataset of Expert Telemedicine Conversations in Bengali",
    thumbnail_url: "/wall/research_1.jpg",
    description: "- Developed DocTalkBN, a large-scale multimodal dataset of real-world expert Bengali telemedicine conversations\n- Collected 557.63 hours of audio-text paired data across 1,515 multi-turn doctor-patient calls\n- Curated 1.7M tokens spanning 26 medical specialties with authentic conversational nuance\n- Constructed three standardized downstream benchmarks: medical triage classification, safety evaluation, and medical NER\n- Evaluated LLMs and transformer baselines for clinically grounded medical reasoning in low-resource languages\n- Released open dataset and benchmarks to advance trustworthy conversational clinical AI",
    abstract: "Reliable medical conversational AI requires authentic expert-patient interaction data, yet such datasets remain scarce, especially for low-resource languages such as Bengali. We present DocTalkBN, a large-scale multimodal dataset of real-world expert telemedicine conversations in Bengali, collected from nationally broadcast telemedicine programs featuring board-certified physicians. DocTalkBN contains 557.63 hours of paired audio and text, 1,515 multi-turn patient calls, 10,274 host-doctor question-answer exchanges, totaling 1.7M tokens, spanning 26 medical specialties. Unlike prior resources derived from medical forums, written health content, or synthetic data, our dataset preserves the spontaneity, contextual richness, and spoken characteristics of authentic medical interactions in a low-resource setting. To support benchmark-driven research, we further construct three downstream tasks from the corpus: medical triage classification, advice safety evaluation, and medical named entity recognition, and benchmark a diverse set of large language models and encoder-based baselines. Our results show that DocTalkBN is a practically useful resource, particularly for clinically grounded reasoning tasks. We release this resource to facilitate future research on reliable medical NLP and safer, more culturally grounded healthcare systems for low-resource languages.",
    status: "preprint",
    award: "",
    year: "2026",
    topics: "Clinical NLP & LLMs, Clinical AI & Deep Learning",
    authors: "Mst. Fahmida Sultana Naznin|https://github.com/fahmidahossain ; Anik Saha ; Sadatul Islam Sadi ; Ananya Shahrin Promi ; Wahid Al Azad Navid ; Rifat Shahriyar",
    links: "code:https://anonymous.4open.science/r/doctalk ; paper:https://anonymous.4open.science/r/doctalk",
    media: "image:/wall/research_1.jpg",
    is_featured: "false",
    featured_order: "999",
    venue: "Under review — ACL ARR (March 2026)",
    external_url: "https://anonymous.4open.science/r/doctalk",
    has_demo: "true",
    demo_url: "https://anonymous.4open.science/r/doctalk",
    bibtex: ""
  },
  {
    id: "11",
    title: "Less Is More? Selective Visual Attention to High-Importance Regions for Multimodal Radiology Summarization",
    thumbnail_url: "/wall/research_1.jpg",
    description: "- Developed ViTAS (Visual-Text Attention Summarizer) for multimodal radiology report summarization\n- Challenged the assumption that more visual input is always beneficial in Findings-to-Impression generation\n- Combined MedSAM2 lung segmentation, bidirectional cross-attention, and Shapley-guided adaptive patch clustering\n- Selectively focused visual representations on pathology-relevant patches rather than noisy full radiographs\n- Achieved SOTA performance on MIMIC-CXR with 29.25% BLEU-4 and 69.83% ROUGE-L\n- Earned highest expert-rated clinician alignment and human evaluation scores",
    abstract: "Automated radiology report summarization aims to distill verbose findings into concise clinical impressions, but existing multimodal models often struggle with visual noise and fail to meaningfully improve over strong text-only baselines in the FINDINGS to IMPRESSION transformation. We challenge two prevailing assumptions: (1) that more visual input is always better, and (2) that multimodal models add limited value when findings already contain rich image-derived detail. Through controlled ablations on MIMIC-CXR benchmark, we show that selectively focusing on pathology-relevant visual patches rather than full images yields substantially better performance. We introduce ViTAS, Visual-Text Attention Summarizer, a multi-stage pipeline that combines ensemble-guided MedSAM2 lung segmentation, bidirectional cross-attention for multi-view fusion, Shapley-guided adaptive patch clustering, and hierarchical visual tokenization feeding a ViT. ViTAS achieves SOTA results with 29.25% BLEU-4 and 69.83% ROUGE-L, improved factual alignment in qualitative analysis, and the highest expert-rated human evaluation scores. Our findings demonstrate that less but more relevant visual input is not only sufficient but superior for multimodal radiology summarization.",
    status: "preprint",
    award: "",
    year: "2026",
    topics: "Computer Vision & Imaging, Clinical NLP & LLMs",
    authors: "Mst. Fahmida Sultana Naznin|https://github.com/fahmidahossain ; Adnan Ibney Faruq ; Mushfiqur Rahman ; Abrar Zahin Raihan ; Niloy Kumar Mondal ; Md. Mehedi Hasan Shawon ; Md Rakibul Hasan",
    links: "paper:https://arxiv.org/",
    media: "image:/wall/research_1.jpg",
    is_featured: "false",
    featured_order: "999",
    venue: "Under review — ACL ARR (March 2026)",
    external_url: "https://arxiv.org/",
    has_demo: "false",
    demo_url: "",
    bibtex: ""
  },
  {
    id: "12",
    title: "DDS-E-Sim: A Transformer-based Probabilistic Generative Framework for Simulating Error-Prone DNA Sequences for DNA Data Storage",
    thumbnail_url: "https://youtu.be/Wn10w_Qcu5Q?si=R0hNV0o4srLAQzjp",
    description: "- Developed DDS-E-Sim, a transformer-based probabilistic generative framework simulating noisy DNA storage channels\n- Captured realistic error distributions across synthesis, storage, and sequencing pipelines\n- Modeled both stochastic and systematic error patterns including k-mer shifts, indel noise, and transition biases\n- Evaluated on Illumina MiSeq and Oxford Nanopore datasets with error rate deviations of only 0.1% and 0.7%\n- Synthesized 100,743 high-fidelity synthetic DNA oligos across 35,329 sequences at 5X coverage\n- Provided a rapid, cost-effective in-silico simulation alternative to expensive in-vitro wet lab experiments",
    abstract: "DNA has emerged as a promising medium for long-lasting data storage due to its high information density and long-term stability. However, DNA storage is a complex process where each stage introduces noise and errors. Since running DNA data storage experiments in vitro is still expensive and time-consuming, a simulation model is quite necessary that can mimic the error patterns in real data and simulate the experiments. Existing tools often rely on fixed error rates or are specific to certain technologies. We propose DDS-E-Sim, a transformer-based probabilistic generative framework that simulates errors in a DNA data storage channel, regardless of the process or technology. DDS-E-Sim successfully captures the error distribution of DNA storage pipelines and learns to stochastically generate erroneous DNA reads. Given oligos (DNA sequences to write), it outputs erroneous reads resembling real pipelines capturing both random and biased errors, such as k-mer and transition errors. Evaluations on two distinct technology-specific datasets show high fidelity and universality: DDS-E-Sim exhibits a total error rate deviation of only 0.1% and 0.7% respectively on datasets processed with Illumina MiSeq and Oxford Nanopore. Additionally, our simulator generates 100,743 unique oligos from 35,329 sequences, with coverage 5 in the test set.",
    status: "published",
    award: "",
    year: "2025",
    topics: "Clinical AI & Deep Learning, LLMs & Multi-Agent",
    authors: "Mst. Fahmida Sultana Naznin|https://github.com/fahmidahossain ; Swarup Sidhartho Mondol ; Adnan Ibney Faruq ; Debashmita Saha ; Ahmed Mahir Sultan Rumi ; A. B. M. Alim Al Islam",
    links: "paper:https://doi.org/10.1101/2025.02.14.637785v2 ; video:https://youtu.be/Wn10w_Qcu5Q?si=R0hNV0o4srLAQzjp",
    media: "image:/wall/research_1.jpg ; youtube:https://youtu.be/Wn10w_Qcu5Q?si=R0hNV0o4srLAQzjp",
    is_featured: "false",
    featured_order: "999",
    venue: "NeurIPS 2025 Workshop SPIGM",
    external_url: "https://doi.org/10.1101/2025.02.14.637785v2",
    has_demo: "true",
    demo_url: "https://youtu.be/Wn10w_Qcu5Q?si=R0hNV0o4srLAQzjp",
    bibtex: ""
  },
  {
    id: "13",
    title: "ContiFuse-MM: Continuous-Time Multimodal Modeling for Short-Horizon ICU Mortality in Cardiac Dysrhythmias",
    thumbnail_url: "/wall/fahmida_with_purdue.jpeg",
    description: "- Developed ContiFuse-MM for short-horizon ICU mortality prediction in cardiac dysrhythmias\n- Formulated continuous-time neural ODE event modeling to handle irregularly sampled longitudinal EHR telemetry\n- Seamlessly integrated multimodal representations combining asynchronous physiological vitals and chest X-rays\n- Evaluated on MIMIC-IV and MIMIC-CXR benchmark datasets across emergency critical care horizons\n- Designed comprehensive SHAP-based explainability analysis to reveal dynamic clinical deterioration pathways\n- Discovered horizon-specific biomarker trajectories and modality attributions to assist ICU clinical decision-making",
    abstract: "Critical care prognostication in intensive care units (ICUs) requires synthesizing complex, irregularly sampled electronic health record (EHR) time-series with high-resolution radiological imaging. Existing predictive models typically resample or discretize irregular clinical data, leading to information loss and poor sensitivity to acute physiological deterioration in patients with cardiac dysrhythmias. We propose ContiFuse-MM, a novel continuous-time multimodal modeling framework for short-horizon ICU mortality prediction. ContiFuse-MM leverages continuous-time neural processes and multimodal fusion to seamlessly integrate asynchronous, irregularly measured physiological parameters from MIMIC-IV with chest radiograph representations from MIMIC-CXR. Furthermore, we develop a specialized SHAP-based explainability suite that decomposes model predictions into horizon-specific biomarker trajectories, modality attributions, and clinical risk pathways. Extensive evaluations demonstrate that ContiFuse-MM outperforms state-of-the-art multimodal baselines in short-term mortality forecasting, providing both superior predictive precision and actionable, clinically interpretable risk factors for emergency intensive care intervention.",
    status: "preprint",
    award: "",
    year: "2026",
    topics: "Clinical AI & Deep Learning, Multimodal Systems",
    authors: "Mst. Fahmida Sultana Naznin|https://github.com/fahmidahossain ; Mohammad Neamul Kabir",
    links: "paper:https://arxiv.org/",
    media: "image:/wall/fahmida_with_purdue.jpeg",
    is_featured: "true",
    featured_order: "6",
    venue: "Under review — NeurIPS Workshops 2026",
    external_url: "https://arxiv.org/",
    has_demo: "false",
    demo_url: "",
    bibtex: ""
  }
];

const projectsData = [
  {
    id: "1",
    title: "PinkLifeLine: AI-Powered Breast Cancer Early Detection Platform",
    thumbnail_url: "/wall/fahmida_with_lal_background.jpeg",
    description: "Enterprise digital health ecosystem and deep learning framework for early breast cancer detection using longitudinal spatiotemporal LED imaging and mammogram analysis. Architected microservices with Spring Boot, React, WebSocket, RabbitMQ, Docker, Kubernetes, Terraform, and GCP.",
    presented_in: "Startup Bangladesh & Johns Hopkins Design Competition",
    presented_in_url: "https://www.pinklifeline.com/",
    year: "2024",
    keywords: "Medical AI, Deep Learning, Spring Boot, React, Cloud Architecture, Digital Health",
    is_featured: "true",
    featured_order: "1",
    sources: "live_demo:https://www.pinklifeline.com/|Live Platform ; github:https://github.com/fahmidahossain/PinkLifeLine|System Repo ; video:https://youtu.be/0xes6eOvChk?si=i8NVwU5C6QnYGlWz|Product Pitch"
  },
  {
    id: "2",
    title: "Speakio: AI-Powered Multi-Language Learning Platform",
    thumbnail_url: "/wall/fahmida_with_car.jpeg",
    description: "Adaptive multi-language educational platform leveraging generative AI for dynamic lesson synthesis, interactive speech exercises, and real-time pronunciation feedback. Engineered front-end architecture and gamified progression mechanics.",
    presented_in: "EdTech Innovation Showcase",
    presented_in_url: "https://github.com/fahmidahossain/Speakio",
    year: "2025",
    keywords: "Generative AI, NLP, React, Language Learning, Speech Evaluation",
    is_featured: "true",
    featured_order: "2",
    sources: "github:https://github.com/fahmidahossain/Speakio|Source Code ; documentation:https://github.com/fahmidahossain/Speakio#readme|Architecture Docs"
  },
  {
    id: "3",
    title: "Plastic4Perks: Gamified Plastic Recycling with Carbon Tracking",
    thumbnail_url: "/wall/fahmida_with_show_pice.jpeg",
    description: "Sustainability tech ecosystem integrating educational arcade games with QR-based smart plastic collection kiosks. Tracks individual carbon offset metrics, incentivizes recycling through digital rewards, and visualizes lifecycle carbon savings.",
    presented_in: "SustainLaunch Showcase",
    presented_in_url: "https://github.com/fahmidahossain",
    year: "2025",
    keywords: "Sustainability, Gamification, React, Pygame, QR Verification, Carbon Footprint",
    is_featured: "true",
    featured_order: "3",
    sources: "github:https://github.com/fahmidahossain/Plastic4Perks|GitHub Repo ; video:https://youtu.be/OBD1d048dl4?si=cv9qY5deJqk74DxS|Platform Demo"
  },
  {
    id: "4",
    title: "QuickSolve: Decentralized AI Complaint Management System",
    thumbnail_url: "/wall/undergrad.jpeg",
    description: "Blockchain-backed dispute and grievance resolution platform utilizing smart contracts and automated NLP metadata analysis for transparent routing, tamper-proof audit trails, and rapid decentralized escalation.",
    presented_in: "Blockchain Olympiad Bangladesh",
    presented_in_url: "https://bcolbd.org/",
    year: "2025",
    keywords: "Blockchain, Smart Contracts, NLP, Node.js, React, Decentralized Systems",
    is_featured: "true",
    featured_order: "4",
    sources: "github:https://github.com/fahmidahossain/QuickSolve|Contract & App Code ; documentation:https://bcolbd.org/|Competition Whitepaper"
  },
  {
    id: "5",
    title: "GreenBlox: Blockchain-Enabled Carbon Credit Market with XGBoost",
    thumbnail_url: "/wall/fahmida_with_robot.jpeg",
    description: "Decentralized carbon credit trading marketplace built on Celo with IoT telemetry integration. Implemented XGBoost predictive models for solar irradiance forecasting and automated verification of solar plant carbon offsets.",
    presented_in: "Global Climate Tech Challenge",
    presented_in_url: "https://isets.org/",
    year: "2024",
    keywords: "Climate Tech, Celo Blockchain, XGBoost, IoT Telemetry, Carbon Credits",
    is_featured: "true",
    featured_order: "5",
    sources: "github:https://github.com/fahmidahossain/GreenBlox|Smart Contracts & ML ; documentation:https://isets.org/|Project Report"
  },
  {
    id: "6",
    title: "NeoScreenix: Smart AI System for Early Breast Cancer Screening",
    thumbnail_url: "/wall/fahmida_with_lal_background.jpeg",
    description: "Grand Prize winning solution at the 2025 Johns Hopkins Healthcare Design Competition. Combines non-invasive portable optical sensors with deep convolutional neural networks for accessible early breast tumor localization.",
    presented_in: "Johns Hopkins University (1st Place Champion)",
    presented_in_url: "https://cbid.bme.jhu.edu/",
    year: "2025",
    keywords: "Clinical AI, Optical Imaging, Global Health, Biomedical Hardware",
    is_featured: "true",
    featured_order: "6",
    sources: "other:https://cbid.bme.jhu.edu/2025/05/01/winners-of-the-2025-johns-hopkins-healthcare-design-competition/|JHU Award Announcement ; video:https://youtu.be/0xes6eOvChk?si=i8NVwU5C6QnYGlWz|Pitch Presentation"
  },
  {
    id: "7",
    title: "CBRS Multi-Platform Stream Parser & LoRA Engine",
    thumbnail_url: "/wall/research_1.jpg",
    description: "High-throughput multilingual NLP stream filter and parser fine-tuned on Llama-3.2-3B via LoRA, achieving 99% filtering accuracy and 35X token efficiency for urgent life-critical blood donation requests on social media.",
    presented_in: "Findings of ACL 2026",
    presented_in_url: "https://github.com/aaniksahaa/CBRS",
    year: "2026",
    keywords: "LLMs, LoRA Fine-Tuning, Stream Processing, Multilingual NLP, Social Computing",
    is_featured: "false",
    featured_order: "999",
    sources: "github:https://github.com/aaniksahaa/CBRS|Open Source Repo ; documentation:https://github.com/aaniksahaa/CBRS#readme|Benchmark Documentation"
  },
  {
    id: "8",
    title: "MedCAR Clinical Multi-Agent Reasoner & Conflict Resolver",
    thumbnail_url: "/wall/research_1.jpg",
    description: "Autonomous clinical AI multi-agent orchestration architecture featuring neural entailment conflict detection, Graph-Based Anatomical Consistency Learning (GACL), and bipolar weighted argumentation over 503 multimodal chest X-ray cases.",
    presented_in: "International Conference on AI in Healthcare 2025",
    presented_in_url: "https://arxiv.org/",
    year: "2025",
    keywords: "Multi-Agent Systems, Medical AI, Conflict Resolution, Knowledge Graphs",
    is_featured: "false",
    featured_order: "999",
    sources: "paper:https://arxiv.org/|arXiv Preprint ; video:https://youtu.be/jyerIT_txG0?si=9RaI6rVtJXlwX0CI|System Architecture Video"
  },
  {
    id: "9",
    title: "ContiFuse-MM: Continuous-Time Multimodal ICU Analytics",
    thumbnail_url: "/wall/fahmida_with_purdue.jpeg",
    description: "Continuous-time neural ordinary differential equation (ODE) framework integrating asynchronous EHR telemetry with chest radiographs from MIMIC-IV and MIMIC-CXR for short-horizon cardiac dysrhythmia mortality prediction with SHAP biomarker discovery.",
    presented_in: "National University of Singapore (SRI) & NeurIPS Workshops",
    presented_in_url: "https://www.comp.nus.edu.sg/",
    year: "2026",
    keywords: "Neural ODEs, Multimodal Fusion, ICU Telemetry, SHAP Biomarkers, Critical Care",
    is_featured: "false",
    featured_order: "999",
    sources: "paper:https://arxiv.org/|Research Manuscript ; other:https://www.comp.nus.edu.sg/|NUS Computing Research"
  },
  {
    id: "10",
    title: "AgroLink: AI-Driven Livestock Health & Weight Estimation",
    thumbnail_url: "/wall/undergrad.jpeg",
    description: "AI-based livestock healthcare and non-contact body weight estimation platform using Seg2Reg-Net Attention U-Net regression, awarded BUET UIHP Cohort-5 seed funding by RISE BUET.",
    presented_in: "RISE BUET UIHP Cohort-5",
    presented_in_url: "https://rise.buet.ac.bd/",
    year: "2025",
    keywords: "Computer Vision, Attention U-Net, Explainable AI, AgriTech",
    is_featured: "false",
    featured_order: "999",
    sources: "github:https://github.com/fahmidahossain/Seg2Reg-Net|Model Code ; video:https://youtu.be/qIXg9vJ6hZM?si=5liTMbMY_VbdWT0r|Project Video Demo"
  }
];

// Write research.csv
const researchCsv = Papa.unparse(researchData, { quotes: true });
fs.writeFileSync(path.join(DATA_DIR, 'research.csv'), researchCsv, 'utf-8');
console.log(`✅ Successfully updated research.csv (${researchData.length} publications)`);

// Write projects.csv
const projectsCsv = Papa.unparse(projectsData, { quotes: true });
fs.writeFileSync(path.join(DATA_DIR, 'projects.csv'), projectsCsv, 'utf-8');
console.log(`✅ Successfully updated projects.csv (${projectsData.length} projects)`);
